### PR TITLE
Convert symlink to copy of file

### PR DESCRIPTION
**Pull request by aequitas**
to hopefully fix https://github.com/ziglang/sublime-zig-language/issues/34

### CODE REVIEW

**Comment by JarrettBillingsley** [comment]
I just installed this package from Package Control and I'm still getting the error from #34 (and the file still looks like a symlink). Am I doing something wrong?

**Comment by aequitas** [comment]
Does the package manager take the release version or the repo master as source? Afaict there has been no release with this commit yet. https://github.com/ziglang/sublime-zig-language/compare/1.4.5...master

**Comment by rwols** [comment]
Can we get a new release with this fix?

**Comment by rwols** [comment]
> Does the package manager take the release version or the repo master as source?

You have `tags` set to `true` in your package entry so package control uses the latest git tag

https://github.com/wbond/package_control_channel/blob/95be4b2baac3519bff69d4398416b95c8ca3e178/repository/z.json#L157

**Pull request merged**
